steps:
# Step 1: Build Docker image
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "$_IMAGE:$SHORT_SHA", "app"]

# Step 2: Push image
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "$_IMAGE:$SHORT_SHA"]

# Step 3: Deploy with Helm
- name: "gcr.io/cloud-builders/gcloud"
  entrypoint: bash
  args:
    - "-c"
    - |
      gcloud container clusters get-credentials $_CLUSTER_NAME --zone $_CLUSTER_ZONE --project $PROJECT_ID
      helm upgrade --install gkeapp ./helm/gkeapp \
        --set image.repository=$_IMAGE \
        --set image.tag=$SHORT_SHA \
        --set service.type=LoadBalancer

substitutions:
  _IMAGE: "us-central1-docker.pkg.dev/$PROJECT_ID/gke-repo/gkeapp"
  _CLUSTER_NAME: "my-gke-cluster"
  _CLUSTER_ZONE: "us-central1-a"

images:
- "$_IMAGE:$SHORT_SHA"

#⚠️ Replace:
#my-gke-cluster with your actual GKE cluster name
#us-central1-a with your cluster’s zone
#gke-repo with your Artifact Registry repo name
#