apiVersion: apps/v1
kind: Deployment
metadata:
  name: gkeapp
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: gkeapp
  template:
    metadata:
      labels:
        app: gkeapp
    spec:
      containers:
      - name: gkeapp
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8080
